### ISSUE TITLE
Link Library without cocoapods in ios

### ISSUE THREAD

**Issue by jaspreetrn** [prscX/react-native-selection-menu#9]
I want to link this library without cocoapods on IOS platform.
and one thing more, can i use this library if i am not using pods in my react native project?

**Comment by prscX** [comment]
Thanks @jaspreetrn for raising the query.

I am afraid to share, considering >= RN61 deep integration with Cocoapods we have also moved the installation completely using pods. `V1` and above we need pods to install the library.

Thanks
</ Pranav >
